site_name: 运维文档
site_url: https://dengyouf.github.io/devops/
repo_url: https://github.com/dengyouf/devops/
nav:
    - 主页: 'index.md'
    - '云原生':
        - '基于kubeadm安装kubernetes集群': 'k8s/install_docker_k8s.md'
    - '服务网格':
          - 'Istio架构概述': 'istio/istio_basics.md'
    - '运行时':
          - '配置Docker代理':  'cri/docker_proxy.md'
    - 'Python开发':
        - 'Python进阶':  'python/advance.md'
theme:
    name: mkdocs
    highlightjs: true
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
use_directory_urls: false
markdown_extensions:
    toc:
        permalink: true
    admonition: {}